version: '3'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
      MYSQL_USER: usr
      MYSQL_PASSWORD: pwd
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql


volumes:
  db:
