version: "3.8"

services:
  postgres:
    container_name: postgres
    image: postgres:12.8
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=dev
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data 
    networks:
      - mysql-compose-network

  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - mysql-compose-network

networks: 
  mysql-compose-network:
    driver: bridge

volumes:
  db:
