version: "3.9"

services:
  postgres:
    container_name: postgres
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - postgres-network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "user@pgadmin.com"
      PGADMIN_DEFAULT_PASSWORD: "PgAdmin2024!"
    ports:
      - "5000:80"
    depends_on:
      - postgres
    networks:
      - postgres-network      

volumes:
  pgdata: {}

networks: 
  postgres-network:
    driver: bridge
