version: '3'

services:
  flyway:
    image: flyway/flyway:6.3.1
    container_name: flyway
    command: -configFiles=/flyway/conf/flyway.config -locations=filesystem:/flyway/sql -connectRetries=60 migrate
    volumes:
      - ${PWD}/sql:/flyway/sql
      - ${PWD}/docker-flyway.config:/flyway/conf/flyway.config
    networks:
      - pg-network
    depends_on:
      - postgres
  postgres:
    image: postgres:12.2
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=test    
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks:
      - pg-network

volumes:
  pg-data:

networks:
  pg-network:
    driver: bridge